### ISSUE TITLE
Дадаць функцыю, які вяртае простае лік па яго індэксе ў паслядоўнасці

### ISSUE THREAD

**Issue by y-gagar1n** [mpMelnikov/WannaBeFullStack#2]
Даволі часта мне не патрэбная ўся паслядоўнасць простых лікаў, а толькі наступнае лік. Я мог бы зрабіць итератор, але для гэтага ваша рэалізацыя алгарытму павінна ўтрымліваць функцыю, якая дазволіць вярнуць i-я простае лік з паслядоўнасці.

Ці можаце вы, калі ласка, дадаць такую функцыю?

**Comment by mpMelnikov** [comment]
@y-gagar1n Правільна я разумею, што трэба дадаць метад, які верне простае лік па індэксе?

**Comment by y-gagar1n** [comment]
Так, менавіта так.
